# backend/services/markdown_formatter.py
from models.schemas import AIAnalysisOutput


class MarkdownFormatter:
    """Formats validated triage results into polished GitHub PR/Commit Markdown comments in pure English."""

    CATEGORY_BADGES = {
        "dependency_issue": "📦 **Dependency Issue / Module Resolution Failure**",
        "syntax_error": "✍️ **Syntax / Type Compilation Error**",
        "type_error": "✍️ **TypeScript Type Mismatch Error**",
        "test_failure": "🧪 **Unit / Integration Test Failure**",
        "flaky_test": "⚠️ **Flaky Test Anomaly**",
        "configuration_error": "⚙️ **Workflow / Configuration Error**",
        "infrastructure_timeout": "⏱️ **Runner Execution Timeout**",
        "runtime_error": "💥 **Runtime Exception**",
        "unknown": "❓ **Unclassified CI Failure**"
    }

    @classmethod
    def format_report(cls, analysis: AIAnalysisOutput, repo_name: str = "", run_id: int = 0, engine_name: str = "Groq (qwen/qwen3.6-27b)") -> str:
        badge = cls.CATEGORY_BADGES.get(
            analysis.failure_category, "❓ **Unclassified Failure**")
        score_percent = round(analysis.confidence_score * 100, 1)

        markdown = f"""### 🤖 CI Failure Triage Bot Diagnostic Report

| **Failure Category** | **Confidence Score** | **AI Model Engine** |
| :--- | :--- | :--- |
| {badge} | `{score_percent}%` | `{engine_name}` |

#### 🔍 Root Cause Analysis
> {analysis.root_cause}

#### 🛠️ Recommended Action & Suggested Fix
```text
{analysis.suggested_fix}
```

---
*Automated diagnostic triage generated by **CI Failure Triage Bot** using `{engine_name}` | Repository: `{repo_name}` | Workflow Run #{run_id}*
"""
        return markdown
